### ISSUE TITLE
Not Work Now

### ISSUE THREAD

**Issue by Mojas84** [jayylmao/catppuccin-nilesoft-shell#2]
Hi. This tutorial with Shell.nss on now not working Nilesoft-Shell Stop Working.........

**Comment by kAMENkitA** [comment]
..mine too..unfortunatelly.. :(

**Comment by jayylmao** [comment]
yeah, i think a recent version changed how themes are applied. still trying to figure out how it works but no guarantees on when i can push a fix to the instructions.

**Comment by jayylmao** [comment]
i've figured out how to get it working now. i'll change the instructions and upload one of the variants (frappe mauve) for now and i'll upload the rest of the variants later on.
<img width="222" alt="image" src="https://github.com/catppuccin/nilesoft-shell/assets/73204320/72364caa-5d27-4b13-95e4-6d6cb7025d2c">

**Comment by Mojas84** [comment]
Thanks Super!!!!!

**Comment by Mojas84** [comment]
Please Mocha-Pink.... 😉

**Comment by kAMENkitA** [comment]
..I will try also to apply usng newly instructions..

**Comment by jayylmao** [comment]
all variants should be up on the repo now.
